### ISSUE TITLE
Unity cant open the project

### ISSUE THREAD

**Issue by EmpireWorld** [KyleStank/Project-SFPS#4]
When i select the project folder unity open bug reporter after loading some things

**Comment by DouglasDRF** [comment]
Can you print screen the bug report? Would be easier find the problem seeing what's in there

**Comment by EmpireWorld** [comment]
![bug-reporter](https://cloud.githubusercontent.com/assets/18309454/17462645/d3813e82-5cc8-11e6-98ab-f8907d125869.png)

**Comment by KyleStank** [comment]
What version of Unity do you have? That is strange, as I cloned every commit to a new folder to make sure everything worked.

**Comment by EmpireWorld** [comment]
Unity Version: 5.3.0
OS: Windows 10

**Comment by KyleStank** [comment]
That is so weird. Try the Unity 5.4 beta tho, because that is what this project is. And if you don't, Unity 5.3 has a huge UNET bug which will break the game anyway. So I highly reccommend Unity 5.4 for this project.

**Comment by EmpireWorld** [comment]
thanks for support, i will do that
thank you very much.
